<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <CompressionEnabled>false</CompressionEnabled>

    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>

    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" />
    <PackageReference Include="Umbraco.StorageProviders.AzureBlob" />
    <PackageReference Include="Umbraco.StorageProviders.AzureBlob.ImageSharp" />
    <PackageReference Include="SeoToolkit.Umbraco" />
    <PackageReference Include="SeoToolkit.Umbraco.Sitemap" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" />
    <RuntimeHostConfigurationOption
      Include="System.Globalization.AppLocalIcu"
      Value="72.1.0.3"
      Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
