-- ROLLBACK ARTIFACT (Phase 2 security cutover)
-- Production anon grant surface BEFORE 20260818120000_anon_grant_lockdown,
-- captured read-only 2026-07-13 from hkpokyapzarefrgqzkos.
-- Apply ONLY to roll back the lockdown (restores the exact pre-lockdown anon surface).
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public._migration_legacy_stub_invoice_lines_archive TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public._migration_legacy_stub_order_items_archive TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public._migration_legacy_stub_orders_archive TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public._migration_legacy_stub_orders_manifest TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public._migration_orders_location_id_backup TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.agreement_change_requests TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.agreement_cleanup_audit TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.agreement_delivery_days TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.agreement_requests TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.agreements TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_action_memory TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_activity_log TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_config TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_config_audit TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_health_checks TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_jobs TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ai_suggestions TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.allergens TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.audit_events TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.billing_adjustments TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.billing_products TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.billing_tax_codes TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.closed_dates TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.companies TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_contracts TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_current_agreement_rules TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_deletions TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_locations TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_memberships TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_product_prices TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.company_registrations TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.content_page_variants TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.content_pages TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.deliveries TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.delivery_run_items TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.delivery_runs TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dietary_tags TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.driver_runs TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.employee_order_items TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.employee_orders TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.enterprise_groups TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.form_submissions TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.forms TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.idempotency TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.incidents TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invoice_lines TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invoice_periods TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invoice_runs TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invoices TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.lead_pipeline TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.lifecycle_audit_log TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.location_closed_dates TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.location_memberships TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.location_policies TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.marketing_pages TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.media_items TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.menu_service_day_items TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.menu_service_days TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.menu_visibility_days TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ops_events TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.order_items TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.order_status_history TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.orders TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.platform_user_roles TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.product_allergens TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.product_categories TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.product_dietary_tags TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.production_days TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.production_manifests TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.products TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.profile_cleanup_audit TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.profile_scope_legacy_write_audit TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.profiles TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.provider_invoices TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.provider_memberships TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.provider_price_rules_tier_defaults_v1 TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.provider_service_areas TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.provider_subscriptions TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.providers TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.repair_jobs TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.social_posts TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.standing_orders TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.system_health_snapshots TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.system_incidents TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.system_settings TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tripletex_customers TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tripletex_exports TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tripletex_invoices TO anon;
GRANT EXECUTE ON FUNCTION public.agreement_delivery_days_array(p_agreement_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.app_active_location_id() TO anon;
GRANT EXECUTE ON FUNCTION public.app_active_org() TO anon;
GRANT EXECUTE ON FUNCTION public.app_active_role() TO anon;
GRANT EXECUTE ON FUNCTION public.app_is_platform_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.assert_role_valid_for_org() TO anon;
GRANT EXECUTE ON FUNCTION public.audit_direct_profile_scope_write() TO anon;
GRANT EXECUTE ON FUNCTION public.can_access_company(company_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_access_location(location_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_access_provider(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_admin_company(company_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_admin_location(location_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_kitchen_location(location_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.cash_dist(money, money) TO anon;
GRANT EXECUTE ON FUNCTION public.citext(boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.citext(character) TO anon;
GRANT EXECUTE ON FUNCTION public.citext(inet) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_cmp(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_eq(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_ge(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_gt(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_hash(citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_hash_extended(citext, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_larger(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_le(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_lt(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_ne(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_pattern_cmp(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_pattern_ge(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_pattern_gt(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_pattern_le(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_pattern_lt(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citext_smaller(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citextin(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.citextout(citext) TO anon;
GRANT EXECUTE ON FUNCTION public.citextrecv(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.citextsend(citext) TO anon;
GRANT EXECUTE ON FUNCTION public.claim_repair_jobs(p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_ai_action_memory() TO anon;
GRANT EXECUTE ON FUNCTION public.current_profile_active() TO anon;
GRANT EXECUTE ON FUNCTION public.current_profile_company_id() TO anon;
GRANT EXECUTE ON FUNCTION public.current_profile_location_id() TO anon;
GRANT EXECUTE ON FUNCTION public.current_profile_role() TO anon;
GRANT EXECUTE ON FUNCTION public.date_dist(date, date) TO anon;
GRANT EXECUTE ON FUNCTION public.ensure_invoice_head(p_run_id uuid, p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.extract_agreement_delivery_days(p_delivery_days jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.float4_dist(real, real) TO anon;
GRANT EXECUTE ON FUNCTION public.float8_dist(double precision, double precision) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_consistent(internal, bit, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_same(gbtreekey_var, gbtreekey_var, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bit_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_consistent(internal, boolean, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_same(gbtreekey2, gbtreekey2, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bool_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bpchar_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bpchar_consistent(internal, character, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_consistent(internal, bytea, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_same(gbtreekey_var, gbtreekey_var, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_bytea_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_consistent(internal, money, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_distance(internal, money, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_cash_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_consistent(internal, date, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_distance(internal, date, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_same(gbtreekey8, gbtreekey8, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_date_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_decompress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_consistent(internal, anyenum, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_same(gbtreekey8, gbtreekey8, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_enum_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_consistent(internal, real, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_distance(internal, real, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_same(gbtreekey8, gbtreekey8, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float4_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_consistent(internal, double precision, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_distance(internal, double precision, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_float8_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_consistent(internal, inet, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_inet_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_consistent(internal, smallint, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_distance(internal, smallint, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_same(gbtreekey4, gbtreekey4, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int2_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_consistent(internal, integer, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_distance(internal, integer, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_same(gbtreekey8, gbtreekey8, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int4_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_consistent(internal, bigint, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_distance(internal, bigint, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_int8_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_consistent(internal, interval, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_decompress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_distance(internal, interval, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_same(gbtreekey32, gbtreekey32, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_intv_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_consistent(internal, macaddr8, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad8_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_consistent(internal, macaddr, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_macad_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_consistent(internal, numeric, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_same(gbtreekey_var, gbtreekey_var, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_numeric_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_consistent(internal, oid, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_distance(internal, oid, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_same(gbtreekey8, gbtreekey8, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_oid_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_consistent(internal, text, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_same(gbtreekey_var, gbtreekey_var, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_text_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_consistent(internal, time without time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_distance(internal, time without time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_time_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_timetz_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_timetz_consistent(internal, time with time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_consistent(internal, timestamp without time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_distance(internal, timestamp without time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_same(gbtreekey16, gbtreekey16, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_ts_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_tstz_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_tstz_consistent(internal, timestamp with time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_tstz_distance(internal, timestamp with time zone, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_compress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_consistent(internal, uuid, smallint, oid, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_penalty(internal, internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_picksplit(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_same(gbtreekey32, gbtreekey32, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_uuid_union(internal, internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_var_decompress(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbt_var_fetch(internal) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey16_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey16_out(gbtreekey16) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey2_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey2_out(gbtreekey2) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey32_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey32_out(gbtreekey32) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey4_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey4_out(gbtreekey4) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey8_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey8_out(gbtreekey8) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey_var_in(cstring) TO anon;
GRANT EXECUTE ON FUNCTION public.gbtreekey_var_out(gbtreekey_var) TO anon;
GRANT EXECUTE ON FUNCTION public.int2_dist(smallint, smallint) TO anon;
GRANT EXECUTE ON FUNCTION public.int4_dist(integer, integer) TO anon;
GRANT EXECUTE ON FUNCTION public.int8_dist(bigint, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.interval_dist(interval, interval) TO anon;
GRANT EXECUTE ON FUNCTION public.is_driver() TO anon;
GRANT EXECUTE ON FUNCTION public.is_ops() TO anon;
GRANT EXECUTE ON FUNCTION public.is_platform_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.is_platform_admin_legacy() TO anon;
GRANT EXECUTE ON FUNCTION public.is_platform_admin_or_service() TO anon;
GRANT EXECUTE ON FUNCTION public.is_superadmin() TO anon;
GRANT EXECUTE ON FUNCTION public.jwt_email_lower() TO anon;
GRANT EXECUTE ON FUNCTION public.kitchen_can_read_lp_user_allergen(p_target_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.log_ai_config_changes() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_advisory_lock(p_key text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_agreement_activate(p_agreement_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_agreement_lifecycle_hook() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_assert_company_active(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_batch_transition_and_sync_orders(p_delivery_date date, p_delivery_window text, p_company_location_id uuid, p_target_batch_status text, p_actor_user_id uuid, p_mode text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_apply_payment_recovery_policy(p_provider_invoice_id uuid, p_payment_status text, p_failure_code text, p_failure_message_safe text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_assert_provider_org() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_can_access_provider(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_close_commission_period(p_provider_id uuid, p_period_start date, p_period_end date, p_currency text, p_billing_timezone text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_create_commission_invoice(p_provider_id uuid, p_period_start date, p_period_end date, p_currency text, p_idempotency_key text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_create_order_line_snapshot(p_order_line_id uuid, p_market_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_create_provider_commission_invoice(p_commission_period_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_guard_provider_commission_invoice_update() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_invoice_close_dry_run(p_provider_id uuid, p_period_start date, p_period_end date, p_currency text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_is_provider_admin(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_payment_readiness(p_provider_id uuid, p_period_start date, p_period_end date, p_currency text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_payment_recovery_status(p_provider_invoice_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_post_commission_for_order(p_order_id uuid, p_event_type text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_post_delivered_commission(p_order_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_post_negative_commission_for_order(p_order_id uuid, p_event_type text, p_reason text, p_reference_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_prevent_audit_mutation() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_prevent_commission_ledger_mutation() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_prevent_order_line_snapshot_mutation() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_provider_readiness(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_set_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_billing_stripe_charge_dry_run(p_provider_invoice_id uuid, p_idempotency_key text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_cutoff_context(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_delete(p_company_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_pause(p_company_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_provider_customer_create(p_company_id uuid, p_provider_id uuid, p_env text, p_request_rid text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_register(p_company_name text, p_orgnr text, p_employee_count integer, p_contact_name text, p_contact_email text, p_contact_phone text, p_address_line text, p_postal_code text, p_postal_city text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_registration_approve_provider(p_registration_id uuid, p_agreement_tier text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_registration_create(p_payload jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_registration_reject_provider(p_registration_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_resume(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_company_suspend(p_company_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_delivery_set_status(p_delivery_id uuid, p_status delivery_status, p_proof jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_esg_rollup_month(p_month_start date) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_fundament_is_ops_lm_excluded(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_fundament_map_membership_role(p_role membership_role) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_fundament_map_membership_status(p_status membership_status, p_active boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_fundament_map_profile_role(p_role user_role) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_fundament_map_provider_role(p_role provider_role) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_invoice_build_month(p_month_start date) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_match_provider_by_postal_code(p_postal_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_norm_operative_slot(p_slot text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_order_advance_status(p_order_id uuid, p_target_status text, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_production_freeze_day(p_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_apply_connection_health_check(p_provider_id uuid, p_env text, p_ok boolean, p_auth_failed boolean, p_company_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_complete_onboarding_provisioning(p_provider_id uuid, p_env text, p_summary jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_complete_tripletex_connection(p_provider_id uuid, p_env text, p_tripletex_company_id bigint, p_employee_token text, p_consumer_token text, p_verification_result jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_create(p_slug text, p_name text, p_contact_email text, p_org_number text, p_contact_phone text, p_billing_org_no text, p_billing_email text, p_billing_address text, p_default_tier_pricing text, p_billing_model text, p_request_rid text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_delete(p_provider_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_disconnect_tripletex(p_provider_id uuid, p_env text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_finalize_tripletex_connection(p_provider_id uuid, p_env text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_get_connection_health(p_provider_id uuid, p_env text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_get_tripletex_credentials_status(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_pause(p_provider_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_purge_disconnected_vault(p_provider_id uuid, p_env text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_reconnect_tripletex(p_provider_id uuid, p_env text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_resume(p_provider_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_set_subscription(p_provider_id uuid, p_plan text, p_monthly_amount numeric, p_billing_email text, p_billing_org_number text, p_billing_address text, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_set_tripletex_credentials(p_provider_id uuid, p_env text, p_consumer_token text, p_employee_token text, p_company_id_external bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_suspend(p_provider_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_test_tripletex_token(p_provider_id uuid, p_env text, p_tripletex_company_id bigint, p_employee_token text, p_verification_result jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_update_billing_contact(p_provider_id uuid, p_billing_email text, p_billing_org_number text, p_billing_address text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_provider_update_billing_email(p_organization_id uuid, p_billing_email text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_req_hash(p_payload jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_service_area_save(p_id uuid, p_provider_id uuid, p_city text, p_postal_code_from text, p_postal_code_to text, p_min_employees integer, p_max_employees integer, p_available_days text[], p_active boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_service_area_toggle_active(p_id uuid, p_active boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_touch_invites_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.lp_user_delete(p_user_id uuid, p_reason text, p_gdpr boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_user_pause(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_user_resume(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.lp_user_suspend(p_user_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.normalize_delivery_weekday(input_value text) TO anon;
GRANT EXECUTE ON FUNCTION public.oid_dist(oid, oid) TO anon;
GRANT EXECUTE ON FUNCTION public.oslo_now_ts() TO anon;
GRANT EXECUTE ON FUNCTION public.oslo_time() TO anon;
GRANT EXECUTE ON FUNCTION public.oslo_today() TO anon;
GRANT EXECUTE ON FUNCTION public.project_profile_scope_from_memberships(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.recalculate_invoice_totals_nok(p_invoice_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_match(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_match(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_matches(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_matches(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_replace(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_replace(citext, citext, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_split_to_array(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_split_to_array(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_split_to_table(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.regexp_split_to_table(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.replace(citext, citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.safe_trim(v text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.split_part(citext, citext, integer) TO anon;
GRANT EXECUTE ON FUNCTION public.strpos(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.texticlike(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.texticlike(citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.texticnlike(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.texticnlike(citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.texticregexeq(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.texticregexeq(citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.texticregexne(citext, citext) TO anon;
GRANT EXECUTE ON FUNCTION public.texticregexne(citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.tg_billing_snapshot_order_item() TO anon;
GRANT EXECUTE ON FUNCTION public.time_dist(time without time zone, time without time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.translate(citext, citext, text) TO anon;
GRANT EXECUTE ON FUNCTION public.trg_agreement_change_requests_set_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.ts_dist(timestamp without time zone, timestamp without time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.tstz_dist(timestamp with time zone, timestamp with time zone) TO anon;
