/**
 * FASE 11 — lokalisert fakturatekst (15/15 språk, edge-safe).
 *
 * Faktura bruker COMPANY BILLING LANGUAGE (kjøpers språk):
 *   companies.preferred_locale → markets.invoice_language → nb (fail-closed).
 * Beløp, valutakoder, fakturanummer og kanoniske statuser oversettes ALDRI —
 * kun etiketter. Tall-/datoformat følger markedets Intl-locale (krav 9).
 */

export type InvoiceCopy = {
  invoice: string;
  creditNote: string;
  creditNoteFor: string;
  period: string;
  issued: string;
  due: string;
  days: string;
  recipient: string;
  colDescription: string;
  colType: string;
  colQuantity: string;
  colUnitPrice: string;
  colNet: string;
  colGross: string;
  totalNet: string;
  totalToPay: string;
  totalPaid: string;
  paymentsTitle: string;
  footer: string;
  sellerTaxId: string;
  buyerTaxId: string;
  buyerAddress: string;
  statusLabels: Record<string, string>;
};

const NB: InvoiceCopy = {
  invoice: "Faktura",
  creditNote: "Kreditnota",
  creditNoteFor: "Kreditnota for faktura",
  period: "Periode",
  issued: "Utstedt",
  due: "Forfall",
  days: "dager",
  recipient: "Mottaker",
  colDescription: "Beskrivelse",
  colType: "Type",
  colQuantity: "Antall",
  colUnitPrice: "Enhetspris",
  colNet: "Netto",
  colGross: "Brutto",
  totalNet: "Netto",
  totalToPay: "Å betale",
  totalPaid: "Betalt",
  paymentsTitle: "Registrerte betalinger",
  footer: "Betaling skjer via bankoverføring. Ingen kortbetaling (invoice-only).",
  sellerTaxId: "Selger org./skatte-ID",
  buyerTaxId: "Kjøper org./skatte-ID",
  buyerAddress: "Kjøper adresse",
  statusLabels: {
    DRAFT: "Utkast",
    ISSUED: "Utstedt",
    SENT: "Sendt",
    PARTIALLY_PAID: "Delvis betalt",
    PAID: "Betalt",
    OVERDUE: "Forfalt",
    CREDITED: "Kreditert",
    VOID: "Annullert",
    PENDING_SYNC: "Venter synk",
    SYNC_FAILED: "Synk feilet",
  },
};

const INVOICE_COPY: Record<string, InvoiceCopy> = {
  nb: NB,
  en: {
    invoice: "Invoice",
    creditNote: "Credit note",
    creditNoteFor: "Credit note for invoice",
    period: "Period",
    issued: "Issued",
    due: "Due",
    days: "days",
    recipient: "Recipient",
    colDescription: "Description",
    colType: "Type",
    colQuantity: "Qty",
    colUnitPrice: "Unit price",
    colNet: "Net",
    colGross: "Gross",
    totalNet: "Net",
    totalToPay: "Amount due",
    totalPaid: "Paid",
    paymentsTitle: "Registered payments",
    footer: "Payment is made by bank transfer. No card payment (invoice-only).",
    sellerTaxId: "Seller tax ID",
    buyerTaxId: "Buyer tax ID",
    buyerAddress: "Buyer address",
    statusLabels: { DRAFT: "Draft", ISSUED: "Issued", SENT: "Sent", PARTIALLY_PAID: "Partially paid", PAID: "Paid", OVERDUE: "Overdue", CREDITED: "Credited", VOID: "Void", PENDING_SYNC: "Pending sync", SYNC_FAILED: "Sync failed" },
  },
  sv: {
    invoice: "Faktura",
    creditNote: "Kreditfaktura",
    creditNoteFor: "Kreditfaktura för faktura",
    period: "Period",
    issued: "Utfärdad",
    due: "Förfaller",
    days: "dagar",
    recipient: "Mottagare",
    colDescription: "Beskrivning",
    colType: "Typ",
    colQuantity: "Antal",
    colUnitPrice: "Enhetspris",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "Att betala",
    totalPaid: "Betald",
    paymentsTitle: "Registrerade betalningar",
    footer: "Betalning sker via banköverföring. Ingen kortbetalning (endast faktura).",
    sellerTaxId: "Säljarens organisations-/skatte-ID",
    buyerTaxId: "Köparens organisations-/skatte-ID",
    buyerAddress: "Köparens adress",
    statusLabels: { DRAFT: "Utkast", ISSUED: "Utfärdad", SENT: "Skickad", PARTIALLY_PAID: "Delvis betald", PAID: "Betald", OVERDUE: "Förfallen", CREDITED: "Krediterad", VOID: "Annullerad", PENDING_SYNC: "Väntar på synk", SYNC_FAILED: "Synk misslyckades" },
  },
  da: {
    invoice: "Faktura",
    creditNote: "Kreditnota",
    creditNoteFor: "Kreditnota for faktura",
    period: "Periode",
    issued: "Udstedt",
    due: "Forfald",
    days: "dage",
    recipient: "Modtager",
    colDescription: "Beskrivelse",
    colType: "Type",
    colQuantity: "Antal",
    colUnitPrice: "Enhedspris",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "At betale",
    totalPaid: "Betalt",
    paymentsTitle: "Registrerede betalinger",
    footer: "Betaling sker via bankoverførsel. Ingen kortbetaling (kun faktura).",
    sellerTaxId: "Sælgers CVR-/skatte-ID",
    buyerTaxId: "Købers CVR-/skatte-ID",
    buyerAddress: "Købers adresse",
    statusLabels: { DRAFT: "Udkast", ISSUED: "Udstedt", SENT: "Sendt", PARTIALLY_PAID: "Delvist betalt", PAID: "Betalt", OVERDUE: "Forfalden", CREDITED: "Krediteret", VOID: "Annulleret", PENDING_SYNC: "Afventer synk", SYNC_FAILED: "Synk fejlede" },
  },
  fi: {
    invoice: "Lasku",
    creditNote: "Hyvityslasku",
    creditNoteFor: "Hyvityslasku laskulle",
    period: "Jakso",
    issued: "Laadittu",
    due: "Eräpäivä",
    days: "päivää",
    recipient: "Vastaanottaja",
    colDescription: "Kuvaus",
    colType: "Tyyppi",
    colQuantity: "Määrä",
    colUnitPrice: "Yksikköhinta",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "Maksettava",
    totalPaid: "Maksettu",
    paymentsTitle: "Kirjatut maksut",
    footer: "Maksu suoritetaan tilisiirtona. Ei korttimaksua (vain lasku).",
    sellerTaxId: "Myyjän Y-/verotunnus",
    buyerTaxId: "Ostajan Y-/verotunnus",
    buyerAddress: "Ostajan osoite",
    statusLabels: { DRAFT: "Luonnos", ISSUED: "Laadittu", SENT: "Lähetetty", PARTIALLY_PAID: "Osittain maksettu", PAID: "Maksettu", OVERDUE: "Erääntynyt", CREDITED: "Hyvitetty", VOID: "Mitätöity", PENDING_SYNC: "Odottaa synkronointia", SYNC_FAILED: "Synkronointi epäonnistui" },
  },
  de: {
    invoice: "Rechnung",
    creditNote: "Gutschrift",
    creditNoteFor: "Gutschrift zur Rechnung",
    period: "Zeitraum",
    issued: "Ausgestellt",
    due: "Fällig",
    days: "Tage",
    recipient: "Empfänger",
    colDescription: "Beschreibung",
    colType: "Typ",
    colQuantity: "Menge",
    colUnitPrice: "Einzelpreis",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "Zu zahlen",
    totalPaid: "Bezahlt",
    paymentsTitle: "Erfasste Zahlungen",
    footer: "Die Zahlung erfolgt per Banküberweisung. Keine Kartenzahlung (nur Rechnung).",
    sellerTaxId: "Steuer-/USt-IdNr. des Verkäufers",
    buyerTaxId: "Steuer-/USt-IdNr. des Käufers",
    buyerAddress: "Adresse des Käufers",
    statusLabels: { DRAFT: "Entwurf", ISSUED: "Ausgestellt", SENT: "Versendet", PARTIALLY_PAID: "Teilweise bezahlt", PAID: "Bezahlt", OVERDUE: "Überfällig", CREDITED: "Gutgeschrieben", VOID: "Storniert", PENDING_SYNC: "Synchronisierung ausstehend", SYNC_FAILED: "Synchronisierung fehlgeschlagen" },
  },
  fr: {
    invoice: "Facture",
    creditNote: "Avoir",
    creditNoteFor: "Avoir sur la facture",
    period: "Période",
    issued: "Émise",
    due: "Échéance",
    days: "jours",
    recipient: "Destinataire",
    colDescription: "Description",
    colType: "Type",
    colQuantity: "Qté",
    colUnitPrice: "Prix unitaire",
    colNet: "Net",
    colGross: "Brut",
    totalNet: "Net",
    totalToPay: "À payer",
    totalPaid: "Payé",
    paymentsTitle: "Paiements enregistrés",
    footer: "Le paiement s'effectue par virement bancaire. Pas de paiement par carte (facture uniquement).",
    sellerTaxId: "Identifiant fiscal du vendeur",
    buyerTaxId: "Identifiant fiscal de l'acheteur",
    buyerAddress: "Adresse de l'acheteur",
    statusLabels: { DRAFT: "Brouillon", ISSUED: "Émise", SENT: "Envoyée", PARTIALLY_PAID: "Partiellement payée", PAID: "Payée", OVERDUE: "En retard", CREDITED: "Créditée", VOID: "Annulée", PENDING_SYNC: "Synchronisation en attente", SYNC_FAILED: "Échec de synchronisation" },
  },
  es: {
    invoice: "Factura",
    creditNote: "Factura rectificativa",
    creditNoteFor: "Factura rectificativa de la factura",
    period: "Periodo",
    issued: "Emitida",
    due: "Vencimiento",
    days: "días",
    recipient: "Destinatario",
    colDescription: "Descripción",
    colType: "Tipo",
    colQuantity: "Cant.",
    colUnitPrice: "Precio unitario",
    colNet: "Neto",
    colGross: "Bruto",
    totalNet: "Neto",
    totalToPay: "A pagar",
    totalPaid: "Pagado",
    paymentsTitle: "Pagos registrados",
    footer: "El pago se realiza por transferencia bancaria. Sin pago con tarjeta (solo factura).",
    sellerTaxId: "NIF del vendedor",
    buyerTaxId: "NIF del comprador",
    buyerAddress: "Dirección del comprador",
    statusLabels: { DRAFT: "Borrador", ISSUED: "Emitida", SENT: "Enviada", PARTIALLY_PAID: "Parcialmente pagada", PAID: "Pagada", OVERDUE: "Vencida", CREDITED: "Rectificada", VOID: "Anulada", PENDING_SYNC: "Sincronización pendiente", SYNC_FAILED: "Error de sincronización" },
  },
  it: {
    invoice: "Fattura",
    creditNote: "Nota di credito",
    creditNoteFor: "Nota di credito per la fattura",
    period: "Periodo",
    issued: "Emessa",
    due: "Scadenza",
    days: "giorni",
    recipient: "Destinatario",
    colDescription: "Descrizione",
    colType: "Tipo",
    colQuantity: "Qtà",
    colUnitPrice: "Prezzo unitario",
    colNet: "Netto",
    colGross: "Lordo",
    totalNet: "Netto",
    totalToPay: "Da pagare",
    totalPaid: "Pagato",
    paymentsTitle: "Pagamenti registrati",
    footer: "Il pagamento avviene tramite bonifico bancario. Nessun pagamento con carta (solo fattura).",
    sellerTaxId: "Partita IVA del venditore",
    buyerTaxId: "Partita IVA dell'acquirente",
    buyerAddress: "Indirizzo dell'acquirente",
    statusLabels: { DRAFT: "Bozza", ISSUED: "Emessa", SENT: "Inviata", PARTIALLY_PAID: "Parzialmente pagata", PAID: "Pagata", OVERDUE: "Scaduta", CREDITED: "Accreditata", VOID: "Annullata", PENDING_SYNC: "Sincronizzazione in attesa", SYNC_FAILED: "Sincronizzazione non riuscita" },
  },
  nl: {
    invoice: "Factuur",
    creditNote: "Creditnota",
    creditNoteFor: "Creditnota voor factuur",
    period: "Periode",
    issued: "Uitgegeven",
    due: "Vervaldatum",
    days: "dagen",
    recipient: "Ontvanger",
    colDescription: "Omschrijving",
    colType: "Type",
    colQuantity: "Aantal",
    colUnitPrice: "Stukprijs",
    colNet: "Netto",
    colGross: "Bruto",
    totalNet: "Netto",
    totalToPay: "Te betalen",
    totalPaid: "Betaald",
    paymentsTitle: "Geregistreerde betalingen",
    footer: "Betaling gebeurt via bankoverschrijving. Geen kaartbetaling (alleen factuur).",
    sellerTaxId: "Btw-/fiscaal nummer verkoper",
    buyerTaxId: "Btw-/fiscaal nummer koper",
    buyerAddress: "Adres koper",
    statusLabels: { DRAFT: "Concept", ISSUED: "Uitgegeven", SENT: "Verzonden", PARTIALLY_PAID: "Gedeeltelijk betaald", PAID: "Betaald", OVERDUE: "Achterstallig", CREDITED: "Gecrediteerd", VOID: "Geannuleerd", PENDING_SYNC: "Synchronisatie in behandeling", SYNC_FAILED: "Synchronisatie mislukt" },
  },
  pl: {
    invoice: "Faktura",
    creditNote: "Faktura korygująca",
    creditNoteFor: "Faktura korygująca do faktury",
    period: "Okres",
    issued: "Wystawiona",
    due: "Termin płatności",
    days: "dni",
    recipient: "Odbiorca",
    colDescription: "Opis",
    colType: "Typ",
    colQuantity: "Ilość",
    colUnitPrice: "Cena jednostkowa",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "Do zapłaty",
    totalPaid: "Zapłacono",
    paymentsTitle: "Zarejestrowane płatności",
    footer: "Płatność przelewem bankowym. Brak płatności kartą (tylko faktura).",
    sellerTaxId: "NIP sprzedawcy",
    buyerTaxId: "NIP nabywcy",
    buyerAddress: "Adres nabywcy",
    statusLabels: { DRAFT: "Wersja robocza", ISSUED: "Wystawiona", SENT: "Wysłana", PARTIALLY_PAID: "Częściowo opłacona", PAID: "Opłacona", OVERDUE: "Zaległa", CREDITED: "Skorygowana", VOID: "Anulowana", PENDING_SYNC: "Oczekuje na synchronizację", SYNC_FAILED: "Synchronizacja nieudana" },
  },
  ro: {
    invoice: "Factură",
    creditNote: "Factură storno",
    creditNoteFor: "Factură storno pentru factura",
    period: "Perioadă",
    issued: "Emisă",
    due: "Scadență",
    days: "zile",
    recipient: "Destinatar",
    colDescription: "Descriere",
    colType: "Tip",
    colQuantity: "Cant.",
    colUnitPrice: "Preț unitar",
    colNet: "Net",
    colGross: "Brut",
    totalNet: "Net",
    totalToPay: "De plată",
    totalPaid: "Plătit",
    paymentsTitle: "Plăți înregistrate",
    footer: "Plata se face prin transfer bancar. Fără plată cu cardul (doar factură).",
    sellerTaxId: "CUI/CIF vânzător",
    buyerTaxId: "CUI/CIF cumpărător",
    buyerAddress: "Adresa cumpărătorului",
    statusLabels: { DRAFT: "Ciornă", ISSUED: "Emisă", SENT: "Trimisă", PARTIALLY_PAID: "Parțial plătită", PAID: "Plătită", OVERDUE: "Restantă", CREDITED: "Stornată", VOID: "Anulată", PENDING_SYNC: "Sincronizare în așteptare", SYNC_FAILED: "Sincronizare eșuată" },
  },
  cs: {
    invoice: "Faktura",
    creditNote: "Dobropis",
    creditNoteFor: "Dobropis k faktuře",
    period: "Období",
    issued: "Vystavena",
    due: "Splatnost",
    days: "dní",
    recipient: "Příjemce",
    colDescription: "Popis",
    colType: "Typ",
    colQuantity: "Množství",
    colUnitPrice: "Jednotková cena",
    colNet: "Netto",
    colGross: "Brutto",
    totalNet: "Netto",
    totalToPay: "K úhradě",
    totalPaid: "Uhrazeno",
    paymentsTitle: "Zaznamenané platby",
    footer: "Platba probíhá bankovním převodem. Bez platby kartou (pouze faktura).",
    sellerTaxId: "IČO/DIČ prodávajícího",
    buyerTaxId: "IČO/DIČ kupujícího",
    buyerAddress: "Adresa kupujícího",
    statusLabels: { DRAFT: "Koncept", ISSUED: "Vystavena", SENT: "Odeslána", PARTIALLY_PAID: "Částečně uhrazena", PAID: "Uhrazena", OVERDUE: "Po splatnosti", CREDITED: "Dobropisována", VOID: "Zrušena", PENDING_SYNC: "Čeká na synchronizaci", SYNC_FAILED: "Synchronizace selhala" },
  },
  pt: {
    invoice: "Fatura",
    creditNote: "Nota de crédito",
    creditNoteFor: "Nota de crédito para a fatura",
    period: "Período",
    issued: "Emitida",
    due: "Vencimento",
    days: "dias",
    recipient: "Destinatário",
    colDescription: "Descrição",
    colType: "Tipo",
    colQuantity: "Qtd.",
    colUnitPrice: "Preço unitário",
    colNet: "Líquido",
    colGross: "Bruto",
    totalNet: "Líquido",
    totalToPay: "A pagar",
    totalPaid: "Pago",
    paymentsTitle: "Pagamentos registados",
    footer: "O pagamento é efetuado por transferência bancária. Sem pagamento com cartão (apenas fatura).",
    sellerTaxId: "NIF do vendedor",
    buyerTaxId: "NIF do comprador",
    buyerAddress: "Morada do comprador",
    statusLabels: { DRAFT: "Rascunho", ISSUED: "Emitida", SENT: "Enviada", PARTIALLY_PAID: "Parcialmente paga", PAID: "Paga", OVERDUE: "Vencida", CREDITED: "Creditada", VOID: "Anulada", PENDING_SYNC: "Sincronização pendente", SYNC_FAILED: "Falha na sincronização" },
  },
  el: {
    invoice: "Τιμολόγιο",
    creditNote: "Πιστωτικό τιμολόγιο",
    creditNoteFor: "Πιστωτικό τιμολόγιο για το τιμολόγιο",
    period: "Περίοδος",
    issued: "Εκδόθηκε",
    due: "Λήξη",
    days: "ημέρες",
    recipient: "Παραλήπτης",
    colDescription: "Περιγραφή",
    colType: "Τύπος",
    colQuantity: "Ποσότητα",
    colUnitPrice: "Τιμή μονάδας",
    colNet: "Καθαρό",
    colGross: "Μικτό",
    totalNet: "Καθαρό",
    totalToPay: "Προς πληρωμή",
    totalPaid: "Πληρωμένο",
    paymentsTitle: "Καταχωρημένες πληρωμές",
    footer: "Η πληρωμή γίνεται με τραπεζικό έμβασμα. Χωρίς πληρωμή με κάρτα (μόνο τιμολόγιο).",
    sellerTaxId: "ΑΦΜ πωλητή",
    buyerTaxId: "ΑΦΜ αγοραστή",
    buyerAddress: "Διεύθυνση αγοραστή",
    statusLabels: { DRAFT: "Πρόχειρο", ISSUED: "Εκδόθηκε", SENT: "Στάλθηκε", PARTIALLY_PAID: "Μερικώς πληρωμένο", PAID: "Πληρωμένο", OVERDUE: "Ληξιπρόθεσμο", CREDITED: "Πιστώθηκε", VOID: "Ακυρώθηκε", PENDING_SYNC: "Εκκρεμεί συγχρονισμός", SYNC_FAILED: "Αποτυχία συγχρονισμού" },
  },
};

export const INVOICE_COPY_LANGUAGES = Object.keys(INVOICE_COPY);

/** Fail-closed: ukjent språk → nb (plattformens standard). */
export function invoiceCopyForLanguage(language: string | null | undefined): InvoiceCopy {
  const key = String(language ?? "").trim().toLowerCase();
  return INVOICE_COPY[key] ?? NB;
}
