/**
 * Internal link auto-builder capability: autoGenerateLinks.
 * Generates internal link suggestions for one page or site-wide (batch).
 * Single-page: same as generateInternalLinks. Site-wide: iterates pages and aggregates suggestions with fromPath.
 * Deterministic; no LLM. Import this module to register the capability.
 */

import type { Capability } from "../../capabilityRegistry";
import { registerCapability } from "../../capabilityRegistry";
import {
  generateInternalLinks,
  type PageContentInput,
  type SiteGraphNode,
} from "./generateInternalLinks";

const CAPABILITY_NAME = "autoGenerateLinks";

const autoGenerateLinksCapability: Capability = {
  name: CAPABILITY_NAME,
  description:
    "Internal link auto-builder: generates internal link suggestions for one page (pageContent + siteGraph) or site-wide from siteGraph. Returns suggested links with fromPath, toPath, anchorText, toTitle, reason, priority. Deterministic; no LLM.",
  requiredContext: ["siteGraph"],
  inputSchema: {
    type: "object",
    description: "Auto-generate internal links input",
    properties: {
      siteGraph: {
        type: "array",
        description: "Site graph: pages (path, title, optional keywords, excerpt)",
        items: {
          type: "object",
          required: ["path", "title"],
          properties: {
            path: { type: "string" },
            title: { type: "string" },
            keywords: { type: "array", items: { type: "string" } },
            excerpt: { type: "string" },
          },
        },
      },
      pageContent: {
        type: "object",
        description: "If set, suggest links only for this page (single-page mode)",
        properties: {
          path: { type: "string" },
          title: { type: "string" },
          blocks: { type: "array", items: { type: "object" } },
          plainText: { type: "string" },
        },
      },
      pagesToProcess: {
        type: "array",
        description: "In site-wide mode, only these paths (default: all in siteGraph)",
        items: { type: "string" },
      },
      maxSuggestionsPerPage: { type: "number", description: "Max links per page (default 8)" },
      maxPagesToProcess: { type: "number", description: "In batch, max pages to process (default 50)" },
      locale: { type: "string", description: "Locale (nb | en) for reason copy" },
    },
    required: ["siteGraph"],
  },
  outputSchema: {
    type: "object",
    description: "Auto-generated internal link suggestions",
    required: ["suggestedLinks", "summary"],
    properties: {
      suggestedLinks: {
        type: "array",
        items: {
          type: "object",
          required: ["fromPath", "toPath", "anchorText", "toTitle"],
          properties: {
            fromPath: { type: "string", description: "Source page path" },
            toPath: { type: "string", description: "Target page path" },
            anchorText: { type: "string" },
            toTitle: { type: "string" },
            reason: { type: "string" },
            priority: { type: "string", description: "low | medium | high" },
            blockId: { type: "string" },
          },
        },
      },
      summary: { type: "string" },
      generatedAt: { type: "string", description: "ISO timestamp" },
    },
  },
  safetyConstraints: [
    { code: "suggestions_only", description: "Output is link suggestions only; no content mutation.", enforce: "hard" },
  ],
  targetSurfaces: ["backoffice", "editor", "api"],
};

registerCapability(autoGenerateLinksCapability);

export type AutoGenerateLinksInput = {
  siteGraph: SiteGraphNode[];
  pageContent?: PageContentInput | null;
  pagesToProcess?: string[] | null;
  maxSuggestionsPerPage?: number | null;
  maxPagesToProcess?: number | null;
  locale?: "nb" | "en" | null;
};

export type AutoGeneratedLink = {
  fromPath: string;
  toPath: string;
  anchorText: string;
  toTitle: string;
  reason?: string | null;
  priority?: "low" | "medium" | "high" | null;
  blockId?: string | null;
};

export type AutoGenerateLinksOutput = {
  suggestedLinks: AutoGeneratedLink[];
  summary: string;
  generatedAt: string;
};

function normalizePath(p: string): string {
  return (p ?? "").trim().replace(/\/$/, "") || "/";
}

/**
 * Auto-generates internal link suggestions for one page or site-wide.
 * Single-page: uses pageContent + siteGraph. Site-wide: iterates siteGraph (or pagesToProcess), calls generateInternalLinks per page, aggregates with fromPath.
 * Deterministic; no external calls.
 */
export function autoGenerateLinks(input: AutoGenerateLinksInput): AutoGenerateLinksOutput {
  const locale = input.locale === "en" ? "en" : "nb";
  const isEn = locale === "en";
  const maxPerPage = Math.min(20, Math.max(1, Math.floor(Number(input.maxSuggestionsPerPage) ?? 8)));
  const maxPages = Math.min(200, Math.max(1, Math.floor(Number(input.maxPagesToProcess) ?? 50)));

  const graph = Array.isArray(input.siteGraph)
    ? input.siteGraph.filter(
        (n): n is SiteGraphNode =>
          n != null && typeof n === "object" && typeof (n as SiteGraphNode).path === "string" && typeof (n as SiteGraphNode).title === "string"
      )
    : [];

  const suggestedLinks: AutoGeneratedLink[] = [];

  if (input.pageContent != null && typeof input.pageContent === "object") {
    const content = input.pageContent as PageContentInput;
    const fromPath = normalizePath(content.path ?? "");
    const result = generateInternalLinks({
      pageContent: content,
      siteGraph: graph,
      maxSuggestions: maxPerPage,
      locale,
    });
    for (const link of result.suggestedInternalLinks ?? []) {
      suggestedLinks.push({
        fromPath,
        toPath: link.toPath ?? "",
        anchorText: link.anchorText ?? link.toTitle ?? "",
        toTitle: link.toTitle ?? "",
        reason: link.reason ?? undefined,
        priority: link.priority ?? undefined,
        blockId: link.blockId ?? undefined,
      });
    }
  } else {
    const pathsToProcess = Array.isArray(input.pagesToProcess)
      ? input.pagesToProcess.map((p) => normalizePath(p)).filter(Boolean)
      : graph.map((n) => normalizePath(n.path));
    const seenFrom = new Set<string>();
    let processed = 0;
    for (const fromPath of pathsToProcess) {
      if (processed >= maxPages) break;
      if (seenFrom.has(fromPath)) continue;
      const node = graph.find((n) => normalizePath(n.path) === fromPath);
      if (!node) continue;
      seenFrom.add(fromPath);
      processed += 1;

      const pageContent: PageContentInput = {
        path: fromPath,
        title: node.title,
        plainText: [node.title, node.excerpt, (node.keywords ?? []).join(" ")].filter(Boolean).join(" "),
      };
      const result = generateInternalLinks({
        pageContent,
        siteGraph: graph,
        maxSuggestions: maxPerPage,
        locale,
      });
      for (const link of result.suggestedInternalLinks ?? []) {
        suggestedLinks.push({
          fromPath,
          toPath: link.toPath ?? "",
          anchorText: link.anchorText ?? link.toTitle ?? "",
          toTitle: link.toTitle ?? "",
          reason: link.reason ?? undefined,
          priority: link.priority ?? undefined,
          blockId: link.blockId ?? undefined,
        });
      }
    }
  }

  const summary = isEn
    ? `Generated ${suggestedLinks.length} internal link suggestion(s) across ${input.pageContent ? "1" : "multiple"} page(s).`
    : `Genererte ${suggestedLinks.length} forslag til interne lenker på ${input.pageContent ? "1" : "flere"} side(r).`;

  return {
    suggestedLinks,
    summary,
    generatedAt: new Date().toISOString(),
  };
}

export { autoGenerateLinksCapability, CAPABILITY_NAME };
